"""Initial migration

Revision ID: b45dc059932c
Revises: 
Create Date: 2026-04-25 12:16:56.374253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45dc059932c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.add_column('enrollments', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('semester_taken', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('lecturer_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'semester')
    op.drop_column('schedules', 'lecturer_name')
    op.drop_column('enrollments', 'semester_taken')
    op.drop_column('enrollments', 'grade')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_column('courses', 'code')
    # ### end Alembic commands ###
